# fly.toml file generated for habitap on 2023-03-27T17:48:38-07:00

app = "habitap"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[env]
  SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  ALGORITHM="HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES=30